name: pytorch3d-renderer

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  - pip:
    - jupyterlab==3.0.9
    - numpy==1.20.1
    - torch==1.7.1
    - torchvision==0.8.2
    - matplotlib
    - scikit-image
    - plotly
    - pycodestyle
